#!/bin/bash
# See skript küsib kasutajalt kellaaega (tundide arvu) ja tervitab vastavalt sellele.

# Küsi kasutajalt kellaaega
read -p "Sisesta aja väärtus (tundide arv): " aeg

# Kontrolli, kas sisestatud aeg on positiivne arv ja vahemikus 0-23
if ! [[ "$aeg" =~ ^[0-9]+$ ]] || [ $aeg -lt 0 ] || [ $aeg -gt 23 ]; then
    echo "Vigane sisend. Palun sisesta positiivne arv vahemikus 0-23."
    exit 1
fi

# Tervita vastavalt sisestatud kellaajale
if [ $aeg -ge 6 ] && [ $aeg -lt 12 ]; then
    echo "Tere hommikust!"
elif [ $aeg -ge 12 ] && [ $aeg -lt 18 ]; then
    echo "Tere päevast!"
elif [ $aeg -ge 18 ] && [ $aeg -lt 22 ]; then
    echo "Tere õhtust!"
else
    echo "Head ööd!"
fi

