#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 kasutajanimi"
else

  kasutajanimi=$1
  # kasutame kasutaja lisamise käsk vajalikute võtmetega
  useradd $kasutajanimi -m -s /bin/bash
  kasu_tulemus=$?


  # $? - viimase! käsu väljund staatus, 0 kui on korras, muu kui on probleem
  if [ $kasu_tulemus -eq 0 ]; then
    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
    cat /etc/passwd | grep $kasutajanimi
    ls -la /home/$kasutajanimi
  else
    echo "probleem kasutaja $kasutajanimi lisamisega"
    echo "probleemi kood on $kasu_tulemus"
  fi
# skripti õige kasutamise kontrolli lõpp
fi

